using System.Collections.Frozen;
using System.Globalization;

namespace NetworkSecurityAuditor.Localization;

public interface ITextResourceProvider
{
    string Get(string key);
}

public sealed class EnglishTextResourceProvider : ITextResourceProvider
{
    private static readonly FrozenDictionary<string, string> Values =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            [nameof(UiText.AppName)] = "Network Security Auditor",
            [nameof(UiText.AppAcronym)] = "NSA",
            [nameof(UiText.AppTagline)] = "Security posture workspace",
            [nameof(UiText.ClientContext)] = "CLIENT / CONTEXT",
            [nameof(UiText.Categories)] = "CATEGORIES",
            [nameof(UiText.Session)] = "SESSION",
            [nameof(UiText.ReportOutput)] = "REPORT OUTPUT",
            [nameof(UiText.ScanProfile)] = "SCAN PROFILE",
            [nameof(UiText.EnvironmentReadiness)] = "ENVIRONMENT READINESS",
            [nameof(UiText.ScanStatus)] = "SCAN STATUS",
            [nameof(UiText.SecurityPosture)] = "SECURITY POSTURE",
            [nameof(UiText.Failed)] = "FAILED",
            [nameof(UiText.Partial)] = "PARTIAL",
            [nameof(UiText.Passed)] = "PASSED",
            [nameof(UiText.NotApplicable)] = "N/A",
            [nameof(UiText.Assessed)] = "ASSESSED",
            [nameof(UiText.Frameworks)] = "FRAMEWORKS",
            [nameof(UiText.Ransomware)] = "Ransomware",
            [nameof(UiText.Domain)] = "Domain",
            [nameof(UiText.ElevenMapped)] = "11 mapped",
            [nameof(UiText.Id)] = "ID",
            [nameof(UiText.Check)] = "Check",
            [nameof(UiText.Status)] = "Status",
            [nameof(UiText.Runtime)] = "Runtime",
            [nameof(UiText.SelectedCheck)] = "SELECTED CHECK",
            [nameof(UiText.Category)] = "CATEGORY",
            [nameof(UiText.Severity)] = "SEVERITY",
            [nameof(UiText.Evidence)] = "EVIDENCE",
            [nameof(UiText.AssessmentStatus)] = "ASSESSMENT STATUS",
            [nameof(UiText.Findings)] = "FINDINGS",
            [nameof(UiText.ComplianceMapping)] = "COMPLIANCE MAPPING",
            [nameof(UiText.RemediationNotes)] = "REMEDIATION NOTES",
            [nameof(UiText.Assignee)] = "ASSIGNEE",
            [nameof(UiText.DueDate)] = "DUE DATE",
            [nameof(UiText.DateFormatHint)] = "yyyy-MM-dd",
            [nameof(UiText.ActivityConsole)] = "Activity Console",
            [nameof(UiText.Scanning)] = "Scanning...",
            [nameof(UiText.SearchPlaceholder)] = "Search ID, check, or category",
            [nameof(UiText.FilterAll)] = "All",
            [nameof(UiText.FilterNotAssessed)] = "Not Assessed",
            [nameof(UiText.StatusPass)] = "Pass",
            [nameof(UiText.StatusPartial)] = "Partial",
            [nameof(UiText.StatusFail)] = "Fail",
            [nameof(UiText.SeverityCritical)] = "CRITICAL",
            [nameof(UiText.SeverityHigh)] = "HIGH",
            [nameof(UiText.SeverityMedium)] = "MEDIUM",
            [nameof(UiText.SeverityLow)] = "LOW",
            [nameof(UiText.SeverityUnknown)] = "UNKNOWN",
            [nameof(UiText.DurationMillisecondsFormat)] = "{0:0} ms",
            [nameof(UiText.DurationUnavailable)] = "--",
            [nameof(UiText.CheckAccessibilityFormat)] = "{0}. {1} severity. {2}. Category {3}. Status {4}. Runtime {5}.",
            [nameof(UiText.CategoryCompletionFormat)] = "{0} of {1} completed",
            [nameof(UiText.CategoryAccessibilityWithScoreFormat)] = "{0}. {1}. {2}. Score {3} percent.",
            [nameof(UiText.CategoryAccessibilityNoScoreFormat)] = "{0}. {1}. {2}. Score not available.",
            [nameof(UiText.ButtonBrowse)] = "Browse",
            [nameof(UiText.ButtonClearFilters)] = "Clear filters",
            [nameof(UiText.ButtonExportReport)] = "Export report",
            [nameof(UiText.ButtonExport)] = "Export",
            [nameof(UiText.ButtonLoadState)] = "Load state",
            [nameof(UiText.ButtonPrivacyMode)] = "Privacy mode",
            [nameof(UiText.ButtonRunScan)] = "Run Scan",
            [nameof(UiText.ButtonSaveState)] = "Save state",
            [nameof(UiText.ButtonStop)] = "Stop",
            [nameof(UiText.ExportHtmlReport)] = "HTML report",
            [nameof(UiText.ExportPdfReport)] = "PDF report",
            [nameof(UiText.ExportFindingsJson)] = "Findings JSON",
            [nameof(UiText.ExportFindingsCsv)] = "Findings CSV",
            [nameof(UiText.ExportSiemJsonl)] = "SIEM JSONL",
            [nameof(UiText.ExportSarif)] = "SARIF",
            [nameof(UiText.ExportAttackNavigator)] = "ATT&CK Navigator",
            [nameof(UiText.ExportDefectDojoJson)] = "DefectDojo JSON",
            [nameof(UiText.ExportOcsfJsonl)] = "OCSF JSONL",
            [nameof(UiText.ExportOscalJson)] = "OSCAL JSON",
            [nameof(UiText.ExportOscalPoamJson)] = "OSCAL POA&M JSON",
            [nameof(UiText.ExportIntuneJson)] = "Intune JSON",
            [nameof(UiText.ExportComplianceSummaryJson)] = "Compliance summary JSON",
            [nameof(UiText.ExportSiemContentPack)] = "SIEM content pack",
            [nameof(UiText.ExportCmmcHtml)] = "CMMC HTML",
            [nameof(UiText.ExportCmmcJson)] = "CMMC JSON",
            [nameof(UiText.ExportAuditState)] = "Audit State",
            [nameof(UiText.ExportAllJson)] = "All JSON",
            [nameof(UiText.OperationSavingAuditState)] = "Saving audit state",
            [nameof(UiText.AutomationBrowseExportFolder)] = "Browse export folder",
            [nameof(UiText.AutomationCategoryProgress)] = "Category progress navigation",
            [nameof(UiText.AutomationClearFilters)] = "Clear active filters",
            [nameof(UiText.AutomationExportCurrentReport)] = "Export current audit report",
            [nameof(UiText.AutomationExportFormat)] = "Export format selector",
            [nameof(UiText.AutomationExportOutputFolder)] = "Export output folder",
            [nameof(UiText.AutomationExportSelected)] = "Export selected format",
            [nameof(UiText.AutomationFilteredChecks)] = "Filtered security checks",
            [nameof(UiText.AutomationLoadState)] = "Load audit state",
            [nameof(UiText.AutomationNoMatchingChecks)] = "No matching checks",
            [nameof(UiText.AutomationPrivacyMode)] = "Privacy mode",
            [nameof(UiText.AutomationResizePanels)] = "Resize checks and inspector panels",
            [nameof(UiText.AutomationSaveState)] = "Save audit state",
            [nameof(UiText.AutomationScanActivity)] = "Scan activity log",
            [nameof(UiText.AutomationScanProfile)] = "Scan profile selector",
            [nameof(UiText.AutomationScanProgress)] = "Scan progress",
            [nameof(UiText.AutomationSearchChecks)] = "Search checks",
            [nameof(UiText.AutomationSelectedInspector)] = "Selected check evidence and remediation inspector",
            [nameof(UiText.AutomationStartScan)] = "Start security scan",
            [nameof(UiText.AutomationStatusFilter)] = "Status filter",
            [nameof(UiText.AutomationStopScan)] = "Stop running scan",
            [nameof(UiText.HelpExportFolder)] = "Folder where selected reports and content packs will be written.",
            [nameof(UiText.HelpDueDate)] = "Use yyyy-MM-dd. Invalid dates are highlighted and not saved.",
            [nameof(UiText.HelpResizePanels)] = "Drag to resize checks and inspector panels.",
            [nameof(UiText.HelpExportReport)] = "Exports the complete audit using the format selected in Report output.",
            [nameof(UiText.ChecksHeadingFormat)] = "Checks - {0}",
            [nameof(UiText.PassCountFormat)] = "Pass: {0}",
            [nameof(UiText.PartialCountFormat)] = "Partial: {0}",
            [nameof(UiText.FailCountFormat)] = "Fail: {0}",
            [nameof(UiText.NotApplicableCountFormat)] = "N/A: {0}",
            [nameof(UiText.NotAssessedCountFormat)] = "Not assessed: {0}",
            [nameof(UiText.ScanProgressAutomationFormat)] = "Scan progress: {0}",
            [nameof(UiText.ScanReadinessAutomationFormat)] = "Scan readiness: {0}",
            [nameof(UiText.FilteredChecksAutomationFormat)] = "Filtered checks: {0}",
            [nameof(UiText.OverallGradeAutomationFormat)] = "Overall security grade: {0}",
            [nameof(UiText.StatusForAutomationFormat)] = "Status for {0}",
            [nameof(UiText.FindingsForAutomationFormat)] = "Findings for {0}",
            [nameof(UiText.EvidenceForAutomationFormat)] = "Evidence for {0}",
            [nameof(UiText.NotesForAutomationFormat)] = "Remediation notes for {0}",
            [nameof(UiText.AssigneeForAutomationFormat)] = "Remediation assignee for {0}",
            [nameof(UiText.DueDateForAutomationFormat)] = "Remediation due date for {0}",
            [nameof(UiText.SaveStatusAutomationFormat)] = "Assessment save status: {0}",
            [nameof(UiText.NoChecksLoaded)] = "No checks loaded",
            [nameof(UiText.VisibleChecksFormat)] = "{0}/{1} visible",
            [nameof(UiText.NoChecksMatch)] = "No checks match this view",
            [nameof(UiText.ClearFiltersDetail)] = "Clear filters or adjust category and status.",
            [nameof(UiText.LoadCatalogDetail)] = "Load the check catalog to begin.",
            [nameof(UiText.NotScanned)] = "Not scanned",
            [nameof(UiText.AssessedOpenFormat)] = "{0} assessed - {1} open",
            [nameof(UiText.PreflightPassedFormat)] = "Pre-flight {0}/{1} passed",
            [nameof(UiText.ReadyForPreflight)] = "Ready for pre-flight",
            [nameof(UiText.OutcomeSummaryFormat)] = "{0} pass - {1} partial - {2} fail",
            [nameof(UiText.ProfileSummaryFormat)] = "{0} profile",
            [nameof(UiText.ScanAlreadyRunning)] = "A scan is already running.",
            [nameof(UiText.EnvironmentStillRunning)] = "Environment detection and pre-flight checks are still running.",
            [nameof(UiText.RunProfileHelpFormat)] = "Run the {0} profile against applicable checks.",
            [nameof(UiText.CancelRunningScan)] = "Cancel the running scan after the active check responds.",
            [nameof(UiText.NoScanRunning)] = "No scan is currently running.",
            [nameof(UiText.ProfileLocked)] = "Profile selection is locked until the running scan finishes.",
            [nameof(UiText.ChooseProfileFormat)] = "Choose the check set for the next scan. Current profile: {0}.",
            [nameof(UiText.PrivacyModeHelp)] = "Redacts host, domain, tenant, client, and user identifiers from exported reports.",
            [nameof(UiText.SaveUnavailableScanning)] = "Saving audit state is unavailable while a scan is updating results.",
            [nameof(UiText.SaveUnavailableExporting)] = "Saving audit state is unavailable while a report is exporting.",
            [nameof(UiText.SaveStateHelp)] = "Save statuses, evidence, and remediation tracking to an audit state file.",
            [nameof(UiText.LoadUnavailableScanning)] = "Loading audit state is unavailable while a scan is updating results.",
            [nameof(UiText.LoadUnavailableExporting)] = "Loading audit state is unavailable while a report is exporting.",
            [nameof(UiText.LoadStateHelp)] = "Restore statuses, evidence, and remediation tracking from an audit state file.",
            [nameof(UiText.AssessmentChanging)] = "Assessment changing during scan",
            [nameof(UiText.ExportInProgress)] = "Report export in progress",
            [nameof(UiText.UnsavedChanges)] = "Unsaved assessment changes",
            [nameof(UiText.NoUnsavedChanges)] = "No unsaved assessment changes",
            [nameof(UiText.DetectingEnvironment)] = "Detecting environment",
            [nameof(UiText.ReadyCountFormat)] = "{0}/{1} ready",
            [nameof(UiText.PreflightPending)] = "Pre-flight pending",
            [nameof(UiText.Pending)] = "Pending",
            [nameof(UiText.Idle)] = "Idle",
            [nameof(UiText.ScanningPercentFormat)] = "Scanning {0:0}%",
            [nameof(UiText.ScanningStatus)] = "Scanning",
            [nameof(UiText.ExportingReport)] = "Exporting report",
            [nameof(UiText.Ready)] = "Ready",
            [nameof(UiText.ExportComplete)] = "Export complete",
            [nameof(UiText.StateLoaded)] = "State loaded",
            [nameof(UiText.StateSaved)] = "State saved",
            [nameof(UiText.AwaitingAssessment)] = "Awaiting assessment",
            [nameof(UiText.StrongPosture)] = "Strong posture",
            [nameof(UiText.ManagedRisk)] = "Managed risk",
            [nameof(UiText.ModerateRisk)] = "Moderate risk",
            [nameof(UiText.HighRisk)] = "High risk",
            [nameof(UiText.CriticalRisk)] = "Critical risk",
            [nameof(UiText.Unknown)] = "Unknown",
            [nameof(UiText.ExportingFormat)] = "Exporting {0}...",
            [nameof(UiText.PreparingWorkspace)] = "Preparing the audit workspace",
            [nameof(UiText.AssessedExportReadyFormat)] = "{0} assessed - export ready",
            [nameof(UiText.ReadyLocalChecks)] = "Ready to run local audit checks",
            [nameof(UiText.ReadyToScan)] = "Ready to scan",
            [nameof(UiText.ReadyWithAdvisoriesFormat)] = "Ready with {0} pre-flight advisories",
            [nameof(UiText.ExportPaused)] = "Export pauses while a scan is running.",
            [nameof(UiText.ChooseExportFolder)] = "Choose an export folder before exporting.",
            [nameof(UiText.ReadyToExportFormat)] = "Ready to export {0}.",
            [nameof(UiText.RunBeforeExport)] = "Run a scan or mark at least one check before exporting.",
            [nameof(UiText.DomainJoined)] = "Domain joined",
            [nameof(UiText.StatusNotAssessed)] = "Not assessed",
            [nameof(UiText.StatusNotApplicable)] = "N/A",
            [nameof(UiText.RuntimeNotRun)] = "not run",
            [nameof(UiText.HealthNotApplicable)] = "Not applicable",
            [nameof(UiText.HealthOpen)] = "Open",
            [nameof(UiText.HealthInProgress)] = "In progress",
            [nameof(UiText.HealthReview)] = "Review",
            [nameof(UiText.HealthPartial)] = "Partial",
            [nameof(UiText.HealthClear)] = "Clear",
            [nameof(UiText.PreflightPassTag)] = "PASS",
            [nameof(UiText.PreflightWarningTag)] = "WARN",
            [nameof(UiText.PreflightResultFormat)] = "{0}  {1}: {2}",
            [nameof(UiText.PreflightSummaryFormat)] = "Pre-flight: {0}/{1} passed\n{2}",
            [nameof(UiText.PreflightCompleteFormat)] = "Pre-flight complete: {0}/{1} checks passed",
            [nameof(UiText.CatalogLoadedFormat)] = "Catalog loaded: {0} checks across {1} categories",
            [nameof(UiText.ScanStartedFormat)] = "Scan started: {0} profile",
            [nameof(UiText.RunningCheckFormat)] = "Running {0}: {1} ({2}/{3})",
            [nameof(UiText.RunningCheckCompactFormat)] = "Running {0} ({1}/{2})",
            [nameof(UiText.RunningCheckActivityFormat)] = "Running {0}: {1}",
            [nameof(UiText.RunningCheckActivityCompactFormat)] = "Running {0}",
            [nameof(UiText.CompletedCheckFormat)] = "Completed {0}: {1} ({2}/{3})",
            [nameof(UiText.CompletedCheckCompactFormat)] = "Completed {0} ({1}/{2})",
            [nameof(UiText.CompletedCheckActivityFormat)] = "Completed {0}: {1}",
            [nameof(UiText.NoApplicableChecksFormat)] = "No checks in the {0} profile apply to this host/environment.",
            [nameof(UiText.UnsupportedProfileFormat)] = "{0} profile is not available in this preview. No local or Active Directory checks were run.",
            [nameof(UiText.ScanFailedFormat)] = "Scan failed. Review the activity log and crash log: {0}",
            [nameof(UiText.ScanFailedActivityFormat)] = "Scan failed: {0}",
            [nameof(UiText.CrashLogFormat)] = "Crash log: {0}",
            [nameof(UiText.UnexpectedErrorFormat)] = "An unexpected error was handled. Your current audit state is still open.\n\nCrash log: {0}",
            [nameof(UiText.FatalErrorFormat)] = "A fatal error occurred and was written to the crash log.\n\nCrash log: {0}",
            [nameof(UiText.ScanCancelledFormat)] = "Scan cancelled ({0}/{1} completed)",
            [nameof(UiText.ScanCompleteFormat)] = "Scan complete ({0}/{1} checks)",
            [nameof(UiText.GeneratingHtmlReport)] = "Generating HTML report...",
            [nameof(UiText.ReportGeneratedAndOpenedFormat)] = "Report generated and opened: {0}",
            [nameof(UiText.HtmlReportGeneratedAndOpened)] = "HTML report generated and opened",
            [nameof(UiText.ReportGenerationFailedFormat)] = "Report generation or opening failed. Crash log: {0}",
            [nameof(UiText.ReportOpenFailedFormat)] = "Report open failed: {0}",
            [nameof(UiText.Cancelling)] = "Cancelling...",
            [nameof(UiText.ScanCancellationRequested)] = "Scan cancellation requested",
            [nameof(UiText.SelectExportFolder)] = "Select export folder",
            [nameof(UiText.OperationProgressFormat)] = "{0}...",
            [nameof(UiText.ExportingOperationFormat)] = "Exporting {0}",
            [nameof(UiText.OperationFailedFormat)] = "{0} failed. Crash log: {1}",
            [nameof(UiText.OperationFailedActivityFormat)] = "{0} failed: {1}",
            [nameof(UiText.ExportSucceededFormat)] = "{0} exported{1}: {2}",
            [nameof(UiText.ExportActivityFormat)] = "{0} exported",
            [nameof(UiText.SiemPackExportedFormat)] = "SIEM content pack exported: {0} ({1} files)",
            [nameof(UiText.PrivacyModeSuffix)] = " (privacy mode)",
            [nameof(UiText.StateSavedFormat)] = "State saved: {0}",
            [nameof(UiText.StateLoadedFormat)] = "State loaded: {0} checks restored from {1}",
            [nameof(UiText.StateLoadRejectedFormat)] = "State load rejected: {0}",
            [nameof(UiText.StateNotLoadedFormat)] = "State not loaded: {0}",
            [nameof(UiText.StateLoadFailed)] = "Failed to load state file.",
            [nameof(UiText.StateLoadFailedWithLogFormat)] = "Failed to load state file. Crash log: {0}",
            [nameof(UiText.UnsupportedExportFormat)] = "Export format '{0}' is not supported.",
            [nameof(UiText.StatePayloadEmpty)] = "State payload is empty.",
            [nameof(UiText.StateSchemaUnsupportedFormat)] = "Unsupported state schema '{0}'. Expected '{1}'.",
            [nameof(UiText.StateIdentityMissing)] = "State is missing the saved client/machine identity.",
            [nameof(UiText.StateWrongMachineFormat)] = "State belongs to '{0}', not the current machine '{1}'.",
            [nameof(UiText.StateToolVersionMissing)] = "State is missing the tool version.",
            [nameof(UiText.StateTimestampMissing)] = "State is missing its saved timestamp.",
            [nameof(UiText.StateProfileUnsupportedFormat)] = "State contains unsupported scan profile '{0}'.",
            [nameof(UiText.StateThemeUnsupportedFormat)] = "State contains unsupported theme '{0}'.",
            [nameof(UiText.StateChecksMissing)] = "State is missing its check collection.",
            [nameof(UiText.StateCheckIdMissing)] = "State contains a check with no ID.",
            [nameof(UiText.StateDuplicateCheckFormat)] = "State contains duplicate check ID '{0}'.",
            [nameof(UiText.StateInvalidStatusFormat)] = "State contains an invalid status for check '{0}'.",
            [nameof(UiText.StateUnknownChecksFormat)] = "State contains unknown check ID(s): {0}.",
            [nameof(UiText.StateIncompleteFormat)] = "State is incomplete; missing check ID(s): {0}.",
            [nameof(UiText.WindowTitleFormat)] = "{0} v{1}",
            [nameof(UiText.ReportDocumentTitle)] = "Network Security Audit Report",
            [nameof(UiText.ReportBrandedDocumentTitleFormat)] = "{0} - Security Audit Report",
            [nameof(UiText.ReportBrandedHeadingFormat)] = "{0} Security Audit Report",
            [nameof(UiText.ReportCoverSubtitle)] = "Security Assessment Report",
            [nameof(UiText.ReportGeneratedSubtitleFormat)] = "Generated {0} | {1} | {2}",
            [nameof(UiText.ReportFooterFormat)] = "Network Security Auditor v{0}",
            [nameof(UiText.ReportOverallScore)] = "Overall Score",
            [nameof(UiText.ReportRansomwareReadiness)] = "Ransomware Readiness",
            [nameof(UiText.ReportDomainMaturity)] = "Domain Maturity",
            [nameof(UiText.ReportSprsScoreFormat)] = "SPRS Score ({0})",
            [nameof(UiText.ReportOf110)] = "of 110",
            [nameof(UiText.ReportStatusBreakdown)] = "Status Breakdown",
            [nameof(UiText.ReportTopFindings)] = "Top Findings",
            [nameof(UiText.ReportTopFindingsCaption)] = "Top failed and partial findings",
            [nameof(UiText.ReportScoreByCategory)] = "Score by Category",
            [nameof(UiText.ReportScoreByCategoryCaption)] = "Score by category",
            [nameof(UiText.ReportComplianceReadiness)] = "Compliance Framework Readiness",
            [nameof(UiText.ReportComplianceReadinessCaption)] = "Compliance framework readiness",
            [nameof(UiText.ReportRemediationRoadmap)] = "Remediation Roadmap",
            [nameof(UiText.ReportRemediationRoadmapCaption)] = "Failed and partial remediation roadmap",
            [nameof(UiText.ReportDetailedFindings)] = "Detailed Findings",
            [nameof(UiText.ReportDetailedFindingsCaptionFormat)] = "{0} detailed findings",
            [nameof(UiText.ReportFrameworkControlIds)] = "Per-Check Framework Control IDs",
            [nameof(UiText.ReportFrameworkControlIdsCaption)] = "Per-check framework control IDs",
            [nameof(UiText.ReportD3fendCoverage)] = "MITRE D3FEND Defensive Coverage",
            [nameof(UiText.ReportD3fendCoverageCaption)] = "MITRE D3FEND defensive coverage",
            [nameof(UiText.ReportIntuneStigEvidence)] = "Intune STIG Audit Baseline Evidence",
            [nameof(UiText.ReportIntuneStigEvidenceCaption)] = "Imported Intune STIG audit evidence",
            [nameof(UiText.ReportRemediationGuidance)] = "Remediation guidance",
            [nameof(UiText.ReportRemediationGuidanceAriaFormat)] = "Remediation guidance for {0}",
            [nameof(UiText.ReportSource)] = "Source",
            [nameof(UiText.ReportBaseline)] = "Baseline",
            [nameof(UiText.ReportPolicy)] = "Policy",
            [nameof(UiText.ReportExported)] = "Exported",
            [nameof(UiText.ReportError)] = "Error",
            [nameof(UiText.ReportConflict)] = "Conflict",
            [nameof(UiText.ReportNotLicensed)] = "Not licensed",
            [nameof(UiText.ReportNotPermitted)] = "Not permitted",
            [nameof(UiText.ReportImportWarningsFormat)] = "Import warnings: {0} row(s) skipped; {1} header(s) normalized.",
            [nameof(UiText.ReportIntuneSourceLink)] = "Microsoft Intune STIG audit baseline source",
            [nameof(UiText.ReportSourceUrl)] = "Source URL",
            [nameof(UiText.ReportSourceUrlOmitted)] = "Omitted because it is not an HTTP(S) URL.",
            [nameof(UiText.DashboardDocumentTitle)] = "Security Audit Dashboard",
            [nameof(UiText.DashboardTitle)] = "Multi-Client Security Dashboard",
            [nameof(UiText.DashboardSubtitleFormat)] = "Generated {0} UTC | Stale threshold: {1} days | {2} older scan(s) hidden",
            [nameof(UiText.DashboardScanCoverage)] = "Scan Coverage",
            [nameof(UiText.DashboardAverageScore)] = "Average Score",
            [nameof(UiText.DashboardOpenCriticals)] = "Open Criticals",
            [nameof(UiText.DashboardStaleAssets)] = "Stale Assets",
            [nameof(UiText.DashboardActiveExceptions)] = "Active Exceptions",
            [nameof(UiText.DashboardOpenRemediations)] = "Open Remediations",
            [nameof(UiText.DashboardAssetDefinitionFormat)] = "Assets: {0} discovered; {1} valid; {2} scanned; {3} skipped; {4} failed. Scores include latest scorable assets only.",
            [nameof(UiText.DashboardOperationalAging)] = "Operational aging",
            [nameof(UiText.DashboardOldestHigh)] = "Oldest high",
            [nameof(UiText.DashboardOldestCritical)] = "Oldest critical",
            [nameof(UiText.DashboardNotDue)] = "Not due",
            [nameof(UiText.DashboardOverdue1To30)] = "1-30 overdue",
            [nameof(UiText.DashboardOverdue31To60)] = "31-60",
            [nameof(UiText.DashboardOverdue61To90)] = "61-90",
            [nameof(UiText.DashboardOverdue91Plus)] = "91+",
            [nameof(UiText.DashboardNoDueDate)] = "No due date",
            [nameof(UiText.DashboardExposureDefinitionFormat)] = "Exposure ages with evidence: n={0}. Remediation buckets: n={1}; accepted-risk and deferred exceptions are excluded.",
            [nameof(UiText.DashboardEmpty)] = "No scan exports found",
            [nameof(UiText.DashboardEmptyDetail)] = "Place one or more contract-valid *_findings.json exports with Pass, Partial, or Fail findings in this folder, then regenerate the dashboard.",
            [nameof(UiText.DashboardScannedAssets)] = "Scanned assets",
            [nameof(UiText.DashboardScannedAssetsCaption)] = "Latest scorable scan per client and host",
            [nameof(UiText.DashboardFooterFormat)] = "Network Security Auditor v{0} - Dashboard",
            [nameof(UiText.DashboardStale)] = "STALE",
            [nameof(UiText.DashboardOpenReport)] = "Open report",
            [nameof(UiText.DashboardOpenReportAriaFormat)] = "Open report for {0} {1}",
            [nameof(UiText.DashboardOlderDuplicatesFormat)] = "{0} older duplicate scan(s) hidden from the latest-asset table:",
            [nameof(UiText.DashboardLatestDuplicateFormat)] = "{0}: latest for {1} is {2}",
            [nameof(UiText.DashboardExcludedAssetsFormat)] = "{0} valid asset(s) excluded from score coverage:",
            [nameof(UiText.DashboardFailedFilesFormat)] = "{0} input file(s) failed validation:",
            [nameof(UiText.CmmcDocumentTitle)] = "CMMC Self-Assessment Report",
            [nameof(UiText.CmmcTitle)] = "CMMC Level 2 Self-Assessment Report",
            [nameof(UiText.CmmcLevelOne)] = "Level 1 Practices (FAR 52.204-21)",
            [nameof(UiText.CmmcAllControls)] = "All NIST 800-171 Controls",
            [nameof(UiText.CmmcCaption)] = "CMMC control assessment by NIST 800-171 control",
            [nameof(UiText.CmmcControlStatus)] = "Control Status",
            [nameof(UiText.CmmcEligibility)] = "CMMC Level 2 Eligibility",
            [nameof(UiText.CmmcEligibleFull)] = "Eligible (full)",
            [nameof(UiText.CmmcEligibleConditional)] = "Eligible (conditional with POA&M)",
            [nameof(UiText.CmmcNotEligible)] = "Not Eligible",
            [nameof(UiText.CmmcFooterFormat)] = "Network Security Auditor v{0} - CMMC Self-Assessment",
            [nameof(UiText.CmmcStatusMet)] = "Met",
            [nameof(UiText.CmmcStatusNotMet)] = "Not Met",
            [nameof(UiText.CmmcStatusPartiallyMet)] = "Partially Met",
            [nameof(UiText.TableRecommendation)] = "Recommendation",
            [nameof(UiText.TableSeverity)] = "Severity",
            [nameof(UiText.TableEvidence)] = "Evidence",
            [nameof(UiText.TableFindings)] = "Findings",
            [nameof(UiText.TableStatus)] = "Status",
            [nameof(UiText.TableCategory)] = "Category",
            [nameof(UiText.TableAssignee)] = "Assignee",
            [nameof(UiText.TablePass)] = "Pass",
            [nameof(UiText.TableFail)] = "Fail",
            [nameof(UiText.TableFramework)] = "Framework",
            [nameof(UiText.TableMappedChecks)] = "Mapped Checks",
            [nameof(UiText.TableMet)] = "Met",
            [nameof(UiText.TableNotAssessed)] = "Not assessed",
            [nameof(UiText.TableMetCoverage)] = "Met Coverage",
            [nameof(UiText.TablePriority)] = "Priority",
            [nameof(UiText.TableDue)] = "Due",
            [nameof(UiText.TableAttack)] = "ATT&CK",
            [nameof(UiText.TableCheckId)] = "Check ID",
            [nameof(UiText.TableLabel)] = "Label",
            [nameof(UiText.TableFrameworkControls)] = "Framework Controls",
            [nameof(UiText.TableStage)] = "Stage",
            [nameof(UiText.TableChecks)] = "Checks",
            [nameof(UiText.TableTechniques)] = "Techniques",
            [nameof(UiText.TableDevice)] = "Device",
            [nameof(UiText.TableSetting)] = "Setting",
            [nameof(UiText.TableReference)] = "Reference",
            [nameof(UiText.TableLastCheckIn)] = "Last check-in",
            [nameof(UiText.TableControl)] = "Control",
            [nameof(UiText.TableFamily)] = "Family",
            [nameof(UiText.TableWeight)] = "Weight",
            [nameof(UiText.TableDeduction)] = "Deduction",
            [nameof(UiText.TableHost)] = "Host",
            [nameof(UiText.TableClient)] = "Client",
            [nameof(UiText.TableScore)] = "Score",
            [nameof(UiText.TableGrade)] = "Grade",
            [nameof(UiText.TableTrend)] = "Trend",
            [nameof(UiText.TableCritical)] = "Critical",
            [nameof(UiText.TableFails)] = "Fails",
            [nameof(UiText.TableScanDate)] = "Scan Date",
            [nameof(UiText.TableReport)] = "Report",
        }.ToFrozenDictionary(StringComparer.Ordinal);

    public string Get(string key) => Values.TryGetValue(key, out var value)
        ? value
        : throw new KeyNotFoundException($"Unknown UI text resource '{key}'.");

    internal static IReadOnlyDictionary<string, string> Catalog => Values;
}

public static class UiText
{
    private static ITextResourceProvider _provider = new EnglishTextResourceProvider();

    public static ITextResourceProvider Provider
    {
        get => _provider;
        set => _provider = value ?? throw new ArgumentNullException(nameof(value));
    }

    public static string Get(string key) => Provider.Get(key);

    public static string Format(string key, params object?[] arguments) =>
        string.Format(CultureInfo.CurrentCulture, Get(key), arguments);

    internal static IDisposable PushProvider(ITextResourceProvider provider)
    {
        var previous = Provider;
        Provider = provider;
        return new ProviderScope(previous);
    }

    private sealed class ProviderScope(ITextResourceProvider previous) : IDisposable
    {
        private ITextResourceProvider? _previous = previous;

        public void Dispose()
        {
            if (_previous is null)
                return;
            Provider = _previous;
            _previous = null;
        }
    }

    public static string AppName => Get(nameof(AppName));
    public static string AppAcronym => Get(nameof(AppAcronym));
    public static string AppTagline => Get(nameof(AppTagline));
    public static string ClientContext => Get(nameof(ClientContext));
    public static string Categories => Get(nameof(Categories));
    public static string Session => Get(nameof(Session));
    public static string ReportOutput => Get(nameof(ReportOutput));
    public static string ScanProfile => Get(nameof(ScanProfile));
    public static string EnvironmentReadiness => Get(nameof(EnvironmentReadiness));
    public static string ScanStatus => Get(nameof(ScanStatus));
    public static string SecurityPosture => Get(nameof(SecurityPosture));
    public static string Failed => Get(nameof(Failed));
    public static string Partial => Get(nameof(Partial));
    public static string Passed => Get(nameof(Passed));
    public static string NotApplicable => Get(nameof(NotApplicable));
    public static string Assessed => Get(nameof(Assessed));
    public static string Frameworks => Get(nameof(Frameworks));
    public static string Ransomware => Get(nameof(Ransomware));
    public static string Domain => Get(nameof(Domain));
    public static string ElevenMapped => Get(nameof(ElevenMapped));
    public static string Id => Get(nameof(Id));
    public static string Check => Get(nameof(Check));
    public static string Status => Get(nameof(Status));
    public static string Runtime => Get(nameof(Runtime));
    public static string SelectedCheck => Get(nameof(SelectedCheck));
    public static string Category => Get(nameof(Category));
    public static string Severity => Get(nameof(Severity));
    public static string Evidence => Get(nameof(Evidence));
    public static string AssessmentStatus => Get(nameof(AssessmentStatus));
    public static string Findings => Get(nameof(Findings));
    public static string ComplianceMapping => Get(nameof(ComplianceMapping));
    public static string RemediationNotes => Get(nameof(RemediationNotes));
    public static string Assignee => Get(nameof(Assignee));
    public static string DueDate => Get(nameof(DueDate));
    public static string DateFormatHint => Get(nameof(DateFormatHint));
    public static string ActivityConsole => Get(nameof(ActivityConsole));
    public static string Scanning => Get(nameof(Scanning));
    public static string SearchPlaceholder => Get(nameof(SearchPlaceholder));
    public static string FilterAll => Get(nameof(FilterAll));
    public static string FilterNotAssessed => Get(nameof(FilterNotAssessed));
    public static string StatusPass => Get(nameof(StatusPass));
    public static string StatusPartial => Get(nameof(StatusPartial));
    public static string StatusFail => Get(nameof(StatusFail));
    public static string SeverityCritical => Get(nameof(SeverityCritical));
    public static string SeverityHigh => Get(nameof(SeverityHigh));
    public static string SeverityMedium => Get(nameof(SeverityMedium));
    public static string SeverityLow => Get(nameof(SeverityLow));
    public static string SeverityUnknown => Get(nameof(SeverityUnknown));
    public static string DurationMillisecondsFormat => Get(nameof(DurationMillisecondsFormat));
    public static string DurationUnavailable => Get(nameof(DurationUnavailable));
    public static string CheckAccessibilityFormat => Get(nameof(CheckAccessibilityFormat));
    public static string CategoryCompletionFormat => Get(nameof(CategoryCompletionFormat));
    public static string CategoryAccessibilityWithScoreFormat => Get(nameof(CategoryAccessibilityWithScoreFormat));
    public static string CategoryAccessibilityNoScoreFormat => Get(nameof(CategoryAccessibilityNoScoreFormat));
    public static string ButtonBrowse => Get(nameof(ButtonBrowse));
    public static string ButtonClearFilters => Get(nameof(ButtonClearFilters));
    public static string ButtonExportReport => Get(nameof(ButtonExportReport));
    public static string ButtonExport => Get(nameof(ButtonExport));
    public static string ButtonLoadState => Get(nameof(ButtonLoadState));
    public static string ButtonPrivacyMode => Get(nameof(ButtonPrivacyMode));
    public static string ButtonRunScan => Get(nameof(ButtonRunScan));
    public static string ButtonSaveState => Get(nameof(ButtonSaveState));
    public static string ButtonStop => Get(nameof(ButtonStop));
    public static string ExportHtmlReport => Get(nameof(ExportHtmlReport));
    public static string ExportPdfReport => Get(nameof(ExportPdfReport));
    public static string ExportFindingsJson => Get(nameof(ExportFindingsJson));
    public static string ExportFindingsCsv => Get(nameof(ExportFindingsCsv));
    public static string ExportSiemJsonl => Get(nameof(ExportSiemJsonl));
    public static string ExportSarif => Get(nameof(ExportSarif));
    public static string ExportAttackNavigator => Get(nameof(ExportAttackNavigator));
    public static string ExportDefectDojoJson => Get(nameof(ExportDefectDojoJson));
    public static string ExportOcsfJsonl => Get(nameof(ExportOcsfJsonl));
    public static string ExportOscalJson => Get(nameof(ExportOscalJson));
    public static string ExportOscalPoamJson => Get(nameof(ExportOscalPoamJson));
    public static string ExportIntuneJson => Get(nameof(ExportIntuneJson));
    public static string ExportComplianceSummaryJson => Get(nameof(ExportComplianceSummaryJson));
    public static string ExportSiemContentPack => Get(nameof(ExportSiemContentPack));
    public static string ExportCmmcHtml => Get(nameof(ExportCmmcHtml));
    public static string ExportCmmcJson => Get(nameof(ExportCmmcJson));
    public static string ExportAuditState => Get(nameof(ExportAuditState));
    public static string ExportAllJson => Get(nameof(ExportAllJson));
    public static string OperationSavingAuditState => Get(nameof(OperationSavingAuditState));
    public static string AutomationBrowseExportFolder => Get(nameof(AutomationBrowseExportFolder));
    public static string AutomationCategoryProgress => Get(nameof(AutomationCategoryProgress));
    public static string AutomationClearFilters => Get(nameof(AutomationClearFilters));
    public static string AutomationExportCurrentReport => Get(nameof(AutomationExportCurrentReport));
    public static string AutomationExportFormat => Get(nameof(AutomationExportFormat));
    public static string AutomationExportOutputFolder => Get(nameof(AutomationExportOutputFolder));
    public static string AutomationExportSelected => Get(nameof(AutomationExportSelected));
    public static string AutomationFilteredChecks => Get(nameof(AutomationFilteredChecks));
    public static string AutomationLoadState => Get(nameof(AutomationLoadState));
    public static string AutomationNoMatchingChecks => Get(nameof(AutomationNoMatchingChecks));
    public static string AutomationPrivacyMode => Get(nameof(AutomationPrivacyMode));
    public static string AutomationResizePanels => Get(nameof(AutomationResizePanels));
    public static string AutomationSaveState => Get(nameof(AutomationSaveState));
    public static string AutomationScanActivity => Get(nameof(AutomationScanActivity));
    public static string AutomationScanProfile => Get(nameof(AutomationScanProfile));
    public static string AutomationScanProgress => Get(nameof(AutomationScanProgress));
    public static string AutomationSearchChecks => Get(nameof(AutomationSearchChecks));
    public static string AutomationSelectedInspector => Get(nameof(AutomationSelectedInspector));
    public static string AutomationStartScan => Get(nameof(AutomationStartScan));
    public static string AutomationStatusFilter => Get(nameof(AutomationStatusFilter));
    public static string AutomationStopScan => Get(nameof(AutomationStopScan));
    public static string HelpExportFolder => Get(nameof(HelpExportFolder));
    public static string HelpDueDate => Get(nameof(HelpDueDate));
    public static string HelpResizePanels => Get(nameof(HelpResizePanels));
    public static string HelpExportReport => Get(nameof(HelpExportReport));
    public static string ChecksHeadingFormat => Get(nameof(ChecksHeadingFormat));
    public static string PassCountFormat => Get(nameof(PassCountFormat));
    public static string PartialCountFormat => Get(nameof(PartialCountFormat));
    public static string FailCountFormat => Get(nameof(FailCountFormat));
    public static string NotApplicableCountFormat => Get(nameof(NotApplicableCountFormat));
    public static string NotAssessedCountFormat => Get(nameof(NotAssessedCountFormat));
    public static string ScanProgressAutomationFormat => Get(nameof(ScanProgressAutomationFormat));
    public static string ScanReadinessAutomationFormat => Get(nameof(ScanReadinessAutomationFormat));
    public static string FilteredChecksAutomationFormat => Get(nameof(FilteredChecksAutomationFormat));
    public static string OverallGradeAutomationFormat => Get(nameof(OverallGradeAutomationFormat));
    public static string StatusForAutomationFormat => Get(nameof(StatusForAutomationFormat));
    public static string FindingsForAutomationFormat => Get(nameof(FindingsForAutomationFormat));
    public static string EvidenceForAutomationFormat => Get(nameof(EvidenceForAutomationFormat));
    public static string NotesForAutomationFormat => Get(nameof(NotesForAutomationFormat));
    public static string AssigneeForAutomationFormat => Get(nameof(AssigneeForAutomationFormat));
    public static string DueDateForAutomationFormat => Get(nameof(DueDateForAutomationFormat));
    public static string SaveStatusAutomationFormat => Get(nameof(SaveStatusAutomationFormat));
    public static string NoChecksLoaded => Get(nameof(NoChecksLoaded));
    public static string VisibleChecksFormat => Get(nameof(VisibleChecksFormat));
    public static string NoChecksMatch => Get(nameof(NoChecksMatch));
    public static string ClearFiltersDetail => Get(nameof(ClearFiltersDetail));
    public static string LoadCatalogDetail => Get(nameof(LoadCatalogDetail));
    public static string NotScanned => Get(nameof(NotScanned));
    public static string AssessedOpenFormat => Get(nameof(AssessedOpenFormat));
    public static string PreflightPassedFormat => Get(nameof(PreflightPassedFormat));
    public static string ReadyForPreflight => Get(nameof(ReadyForPreflight));
    public static string OutcomeSummaryFormat => Get(nameof(OutcomeSummaryFormat));
    public static string ProfileSummaryFormat => Get(nameof(ProfileSummaryFormat));
    public static string ScanAlreadyRunning => Get(nameof(ScanAlreadyRunning));
    public static string EnvironmentStillRunning => Get(nameof(EnvironmentStillRunning));
    public static string RunProfileHelpFormat => Get(nameof(RunProfileHelpFormat));
    public static string CancelRunningScan => Get(nameof(CancelRunningScan));
    public static string NoScanRunning => Get(nameof(NoScanRunning));
    public static string ProfileLocked => Get(nameof(ProfileLocked));
    public static string ChooseProfileFormat => Get(nameof(ChooseProfileFormat));
    public static string PrivacyModeHelp => Get(nameof(PrivacyModeHelp));
    public static string SaveUnavailableScanning => Get(nameof(SaveUnavailableScanning));
    public static string SaveUnavailableExporting => Get(nameof(SaveUnavailableExporting));
    public static string SaveStateHelp => Get(nameof(SaveStateHelp));
    public static string LoadUnavailableScanning => Get(nameof(LoadUnavailableScanning));
    public static string LoadUnavailableExporting => Get(nameof(LoadUnavailableExporting));
    public static string LoadStateHelp => Get(nameof(LoadStateHelp));
    public static string AssessmentChanging => Get(nameof(AssessmentChanging));
    public static string ExportInProgress => Get(nameof(ExportInProgress));
    public static string UnsavedChanges => Get(nameof(UnsavedChanges));
    public static string NoUnsavedChanges => Get(nameof(NoUnsavedChanges));
    public static string DetectingEnvironment => Get(nameof(DetectingEnvironment));
    public static string ReadyCountFormat => Get(nameof(ReadyCountFormat));
    public static string PreflightPending => Get(nameof(PreflightPending));
    public static string Pending => Get(nameof(Pending));
    public static string Idle => Get(nameof(Idle));
    public static string ScanningPercentFormat => Get(nameof(ScanningPercentFormat));
    public static string ScanningStatus => Get(nameof(ScanningStatus));
    public static string ExportingReport => Get(nameof(ExportingReport));
    public static string Ready => Get(nameof(Ready));
    public static string ExportComplete => Get(nameof(ExportComplete));
    public static string StateLoaded => Get(nameof(StateLoaded));
    public static string StateSaved => Get(nameof(StateSaved));
    public static string AwaitingAssessment => Get(nameof(AwaitingAssessment));
    public static string StrongPosture => Get(nameof(StrongPosture));
    public static string ManagedRisk => Get(nameof(ManagedRisk));
    public static string ModerateRisk => Get(nameof(ModerateRisk));
    public static string HighRisk => Get(nameof(HighRisk));
    public static string CriticalRisk => Get(nameof(CriticalRisk));
    public static string Unknown => Get(nameof(Unknown));
    public static string ExportingFormat => Get(nameof(ExportingFormat));
    public static string PreparingWorkspace => Get(nameof(PreparingWorkspace));
    public static string AssessedExportReadyFormat => Get(nameof(AssessedExportReadyFormat));
    public static string ReadyLocalChecks => Get(nameof(ReadyLocalChecks));
    public static string ReadyToScan => Get(nameof(ReadyToScan));
    public static string ReadyWithAdvisoriesFormat => Get(nameof(ReadyWithAdvisoriesFormat));
    public static string ExportPaused => Get(nameof(ExportPaused));
    public static string ChooseExportFolder => Get(nameof(ChooseExportFolder));
    public static string ReadyToExportFormat => Get(nameof(ReadyToExportFormat));
    public static string RunBeforeExport => Get(nameof(RunBeforeExport));
    public static string DomainJoined => Get(nameof(DomainJoined));
    public static string StatusNotAssessed => Get(nameof(StatusNotAssessed));
    public static string StatusNotApplicable => Get(nameof(StatusNotApplicable));
    public static string RuntimeNotRun => Get(nameof(RuntimeNotRun));
    public static string HealthNotApplicable => Get(nameof(HealthNotApplicable));
    public static string HealthOpen => Get(nameof(HealthOpen));
    public static string HealthInProgress => Get(nameof(HealthInProgress));
    public static string HealthReview => Get(nameof(HealthReview));
    public static string HealthPartial => Get(nameof(HealthPartial));
    public static string HealthClear => Get(nameof(HealthClear));
    public static string PreflightPassTag => Get(nameof(PreflightPassTag));
    public static string PreflightWarningTag => Get(nameof(PreflightWarningTag));
    public static string PreflightResultFormat => Get(nameof(PreflightResultFormat));
    public static string PreflightSummaryFormat => Get(nameof(PreflightSummaryFormat));
    public static string PreflightCompleteFormat => Get(nameof(PreflightCompleteFormat));
    public static string CatalogLoadedFormat => Get(nameof(CatalogLoadedFormat));
    public static string ScanStartedFormat => Get(nameof(ScanStartedFormat));
    public static string RunningCheckFormat => Get(nameof(RunningCheckFormat));
    public static string RunningCheckCompactFormat => Get(nameof(RunningCheckCompactFormat));
    public static string RunningCheckActivityFormat => Get(nameof(RunningCheckActivityFormat));
    public static string RunningCheckActivityCompactFormat => Get(nameof(RunningCheckActivityCompactFormat));
    public static string CompletedCheckFormat => Get(nameof(CompletedCheckFormat));
    public static string CompletedCheckCompactFormat => Get(nameof(CompletedCheckCompactFormat));
    public static string CompletedCheckActivityFormat => Get(nameof(CompletedCheckActivityFormat));
    public static string NoApplicableChecksFormat => Get(nameof(NoApplicableChecksFormat));
    public static string UnsupportedProfileFormat => Get(nameof(UnsupportedProfileFormat));
    public static string ScanFailedFormat => Get(nameof(ScanFailedFormat));
    public static string ScanFailedActivityFormat => Get(nameof(ScanFailedActivityFormat));
    public static string CrashLogFormat => Get(nameof(CrashLogFormat));
    public static string UnexpectedErrorFormat => Get(nameof(UnexpectedErrorFormat));
    public static string FatalErrorFormat => Get(nameof(FatalErrorFormat));
    public static string ScanCancelledFormat => Get(nameof(ScanCancelledFormat));
    public static string ScanCompleteFormat => Get(nameof(ScanCompleteFormat));
    public static string GeneratingHtmlReport => Get(nameof(GeneratingHtmlReport));
    public static string ReportGeneratedAndOpenedFormat => Get(nameof(ReportGeneratedAndOpenedFormat));
    public static string HtmlReportGeneratedAndOpened => Get(nameof(HtmlReportGeneratedAndOpened));
    public static string ReportGenerationFailedFormat => Get(nameof(ReportGenerationFailedFormat));
    public static string ReportOpenFailedFormat => Get(nameof(ReportOpenFailedFormat));
    public static string Cancelling => Get(nameof(Cancelling));
    public static string ScanCancellationRequested => Get(nameof(ScanCancellationRequested));
    public static string SelectExportFolder => Get(nameof(SelectExportFolder));
    public static string OperationProgressFormat => Get(nameof(OperationProgressFormat));
    public static string ExportingOperationFormat => Get(nameof(ExportingOperationFormat));
    public static string OperationFailedFormat => Get(nameof(OperationFailedFormat));
    public static string OperationFailedActivityFormat => Get(nameof(OperationFailedActivityFormat));
    public static string ExportSucceededFormat => Get(nameof(ExportSucceededFormat));
    public static string ExportActivityFormat => Get(nameof(ExportActivityFormat));
    public static string SiemPackExportedFormat => Get(nameof(SiemPackExportedFormat));
    public static string PrivacyModeSuffix => Get(nameof(PrivacyModeSuffix));
    public static string StateSavedFormat => Get(nameof(StateSavedFormat));
    public static string StateLoadedFormat => Get(nameof(StateLoadedFormat));
    public static string StateLoadRejectedFormat => Get(nameof(StateLoadRejectedFormat));
    public static string StateNotLoadedFormat => Get(nameof(StateNotLoadedFormat));
    public static string StateLoadFailed => Get(nameof(StateLoadFailed));
    public static string StateLoadFailedWithLogFormat => Get(nameof(StateLoadFailedWithLogFormat));
    public static string UnsupportedExportFormat => Get(nameof(UnsupportedExportFormat));
    public static string StatePayloadEmpty => Get(nameof(StatePayloadEmpty));
    public static string StateSchemaUnsupportedFormat => Get(nameof(StateSchemaUnsupportedFormat));
    public static string StateIdentityMissing => Get(nameof(StateIdentityMissing));
    public static string StateWrongMachineFormat => Get(nameof(StateWrongMachineFormat));
    public static string StateToolVersionMissing => Get(nameof(StateToolVersionMissing));
    public static string StateTimestampMissing => Get(nameof(StateTimestampMissing));
    public static string StateProfileUnsupportedFormat => Get(nameof(StateProfileUnsupportedFormat));
    public static string StateThemeUnsupportedFormat => Get(nameof(StateThemeUnsupportedFormat));
    public static string StateChecksMissing => Get(nameof(StateChecksMissing));
    public static string StateCheckIdMissing => Get(nameof(StateCheckIdMissing));
    public static string StateDuplicateCheckFormat => Get(nameof(StateDuplicateCheckFormat));
    public static string StateInvalidStatusFormat => Get(nameof(StateInvalidStatusFormat));
    public static string StateUnknownChecksFormat => Get(nameof(StateUnknownChecksFormat));
    public static string StateIncompleteFormat => Get(nameof(StateIncompleteFormat));
    public static string WindowTitleFormat => Get(nameof(WindowTitleFormat));
    public static string ReportDocumentTitle => Get(nameof(ReportDocumentTitle));
    public static string ReportBrandedDocumentTitleFormat => Get(nameof(ReportBrandedDocumentTitleFormat));
    public static string ReportBrandedHeadingFormat => Get(nameof(ReportBrandedHeadingFormat));
    public static string ReportCoverSubtitle => Get(nameof(ReportCoverSubtitle));
    public static string ReportGeneratedSubtitleFormat => Get(nameof(ReportGeneratedSubtitleFormat));
    public static string ReportFooterFormat => Get(nameof(ReportFooterFormat));
    public static string ReportOverallScore => Get(nameof(ReportOverallScore));
    public static string ReportRansomwareReadiness => Get(nameof(ReportRansomwareReadiness));
    public static string ReportDomainMaturity => Get(nameof(ReportDomainMaturity));
    public static string ReportSprsScoreFormat => Get(nameof(ReportSprsScoreFormat));
    public static string ReportOf110 => Get(nameof(ReportOf110));
    public static string ReportStatusBreakdown => Get(nameof(ReportStatusBreakdown));
    public static string ReportTopFindings => Get(nameof(ReportTopFindings));
    public static string ReportTopFindingsCaption => Get(nameof(ReportTopFindingsCaption));
    public static string ReportScoreByCategory => Get(nameof(ReportScoreByCategory));
    public static string ReportScoreByCategoryCaption => Get(nameof(ReportScoreByCategoryCaption));
    public static string ReportComplianceReadiness => Get(nameof(ReportComplianceReadiness));
    public static string ReportComplianceReadinessCaption => Get(nameof(ReportComplianceReadinessCaption));
    public static string ReportRemediationRoadmap => Get(nameof(ReportRemediationRoadmap));
    public static string ReportRemediationRoadmapCaption => Get(nameof(ReportRemediationRoadmapCaption));
    public static string ReportDetailedFindings => Get(nameof(ReportDetailedFindings));
    public static string ReportDetailedFindingsCaptionFormat => Get(nameof(ReportDetailedFindingsCaptionFormat));
    public static string ReportFrameworkControlIds => Get(nameof(ReportFrameworkControlIds));
    public static string ReportFrameworkControlIdsCaption => Get(nameof(ReportFrameworkControlIdsCaption));
    public static string ReportD3fendCoverage => Get(nameof(ReportD3fendCoverage));
    public static string ReportD3fendCoverageCaption => Get(nameof(ReportD3fendCoverageCaption));
    public static string ReportIntuneStigEvidence => Get(nameof(ReportIntuneStigEvidence));
    public static string ReportIntuneStigEvidenceCaption => Get(nameof(ReportIntuneStigEvidenceCaption));
    public static string ReportRemediationGuidance => Get(nameof(ReportRemediationGuidance));
    public static string ReportRemediationGuidanceAriaFormat => Get(nameof(ReportRemediationGuidanceAriaFormat));
    public static string ReportSource => Get(nameof(ReportSource));
    public static string ReportBaseline => Get(nameof(ReportBaseline));
    public static string ReportPolicy => Get(nameof(ReportPolicy));
    public static string ReportExported => Get(nameof(ReportExported));
    public static string ReportError => Get(nameof(ReportError));
    public static string ReportConflict => Get(nameof(ReportConflict));
    public static string ReportNotLicensed => Get(nameof(ReportNotLicensed));
    public static string ReportNotPermitted => Get(nameof(ReportNotPermitted));
    public static string ReportImportWarningsFormat => Get(nameof(ReportImportWarningsFormat));
    public static string ReportIntuneSourceLink => Get(nameof(ReportIntuneSourceLink));
    public static string ReportSourceUrl => Get(nameof(ReportSourceUrl));
    public static string ReportSourceUrlOmitted => Get(nameof(ReportSourceUrlOmitted));
    public static string DashboardDocumentTitle => Get(nameof(DashboardDocumentTitle));
    public static string DashboardTitle => Get(nameof(DashboardTitle));
    public static string DashboardSubtitleFormat => Get(nameof(DashboardSubtitleFormat));
    public static string DashboardScanCoverage => Get(nameof(DashboardScanCoverage));
    public static string DashboardAverageScore => Get(nameof(DashboardAverageScore));
    public static string DashboardOpenCriticals => Get(nameof(DashboardOpenCriticals));
    public static string DashboardStaleAssets => Get(nameof(DashboardStaleAssets));
    public static string DashboardActiveExceptions => Get(nameof(DashboardActiveExceptions));
    public static string DashboardOpenRemediations => Get(nameof(DashboardOpenRemediations));
    public static string DashboardAssetDefinitionFormat => Get(nameof(DashboardAssetDefinitionFormat));
    public static string DashboardOperationalAging => Get(nameof(DashboardOperationalAging));
    public static string DashboardOldestHigh => Get(nameof(DashboardOldestHigh));
    public static string DashboardOldestCritical => Get(nameof(DashboardOldestCritical));
    public static string DashboardNotDue => Get(nameof(DashboardNotDue));
    public static string DashboardOverdue1To30 => Get(nameof(DashboardOverdue1To30));
    public static string DashboardOverdue31To60 => Get(nameof(DashboardOverdue31To60));
    public static string DashboardOverdue61To90 => Get(nameof(DashboardOverdue61To90));
    public static string DashboardOverdue91Plus => Get(nameof(DashboardOverdue91Plus));
    public static string DashboardNoDueDate => Get(nameof(DashboardNoDueDate));
    public static string DashboardExposureDefinitionFormat => Get(nameof(DashboardExposureDefinitionFormat));
    public static string DashboardEmpty => Get(nameof(DashboardEmpty));
    public static string DashboardEmptyDetail => Get(nameof(DashboardEmptyDetail));
    public static string DashboardScannedAssets => Get(nameof(DashboardScannedAssets));
    public static string DashboardScannedAssetsCaption => Get(nameof(DashboardScannedAssetsCaption));
    public static string DashboardFooterFormat => Get(nameof(DashboardFooterFormat));
    public static string DashboardStale => Get(nameof(DashboardStale));
    public static string DashboardOpenReport => Get(nameof(DashboardOpenReport));
    public static string DashboardOpenReportAriaFormat => Get(nameof(DashboardOpenReportAriaFormat));
    public static string DashboardOlderDuplicatesFormat => Get(nameof(DashboardOlderDuplicatesFormat));
    public static string DashboardLatestDuplicateFormat => Get(nameof(DashboardLatestDuplicateFormat));
    public static string DashboardExcludedAssetsFormat => Get(nameof(DashboardExcludedAssetsFormat));
    public static string DashboardFailedFilesFormat => Get(nameof(DashboardFailedFilesFormat));
    public static string CmmcDocumentTitle => Get(nameof(CmmcDocumentTitle));
    public static string CmmcTitle => Get(nameof(CmmcTitle));
    public static string CmmcLevelOne => Get(nameof(CmmcLevelOne));
    public static string CmmcAllControls => Get(nameof(CmmcAllControls));
    public static string CmmcCaption => Get(nameof(CmmcCaption));
    public static string CmmcControlStatus => Get(nameof(CmmcControlStatus));
    public static string CmmcEligibility => Get(nameof(CmmcEligibility));
    public static string CmmcEligibleFull => Get(nameof(CmmcEligibleFull));
    public static string CmmcEligibleConditional => Get(nameof(CmmcEligibleConditional));
    public static string CmmcNotEligible => Get(nameof(CmmcNotEligible));
    public static string CmmcFooterFormat => Get(nameof(CmmcFooterFormat));
    public static string CmmcStatusMet => Get(nameof(CmmcStatusMet));
    public static string CmmcStatusNotMet => Get(nameof(CmmcStatusNotMet));
    public static string CmmcStatusPartiallyMet => Get(nameof(CmmcStatusPartiallyMet));
    public static string TableRecommendation => Get(nameof(TableRecommendation));
    public static string TableSeverity => Get(nameof(TableSeverity));
    public static string TableEvidence => Get(nameof(TableEvidence));
    public static string TableFindings => Get(nameof(TableFindings));
    public static string TableStatus => Get(nameof(TableStatus));
    public static string TableCategory => Get(nameof(TableCategory));
    public static string TableAssignee => Get(nameof(TableAssignee));
    public static string TablePass => Get(nameof(TablePass));
    public static string TableFail => Get(nameof(TableFail));
    public static string TableFramework => Get(nameof(TableFramework));
    public static string TableMappedChecks => Get(nameof(TableMappedChecks));
    public static string TableMet => Get(nameof(TableMet));
    public static string TableNotAssessed => Get(nameof(TableNotAssessed));
    public static string TableMetCoverage => Get(nameof(TableMetCoverage));
    public static string TablePriority => Get(nameof(TablePriority));
    public static string TableDue => Get(nameof(TableDue));
    public static string TableAttack => Get(nameof(TableAttack));
    public static string TableCheckId => Get(nameof(TableCheckId));
    public static string TableLabel => Get(nameof(TableLabel));
    public static string TableFrameworkControls => Get(nameof(TableFrameworkControls));
    public static string TableStage => Get(nameof(TableStage));
    public static string TableChecks => Get(nameof(TableChecks));
    public static string TableTechniques => Get(nameof(TableTechniques));
    public static string TableDevice => Get(nameof(TableDevice));
    public static string TableSetting => Get(nameof(TableSetting));
    public static string TableReference => Get(nameof(TableReference));
    public static string TableLastCheckIn => Get(nameof(TableLastCheckIn));
    public static string TableControl => Get(nameof(TableControl));
    public static string TableFamily => Get(nameof(TableFamily));
    public static string TableWeight => Get(nameof(TableWeight));
    public static string TableDeduction => Get(nameof(TableDeduction));
    public static string TableHost => Get(nameof(TableHost));
    public static string TableClient => Get(nameof(TableClient));
    public static string TableScore => Get(nameof(TableScore));
    public static string TableGrade => Get(nameof(TableGrade));
    public static string TableTrend => Get(nameof(TableTrend));
    public static string TableCritical => Get(nameof(TableCritical));
    public static string TableFails => Get(nameof(TableFails));
    public static string TableScanDate => Get(nameof(TableScanDate));
    public static string TableReport => Get(nameof(TableReport));
}
